@api = http://localhost:8001/auth

### Health Check
GET http://localhost:8001/healthcheck

### Register User
POST {{api}}/register
Content-Type: application/json

{
    "username": "KrizMarles",
    "email": "kriz@gmail.com",
    "password": "kriz_pass"
}


### Login
POST {{api}}/login
Content-Type: application/json

{
    "email": "kriz@gmail.com",
    "password": "kriz_pass"
}
